### ISSUE TITLE
Display subtitles offered by sites

### ISSUE THREAD

**Issue by Movisivi** [gorhill/ccaptioner#2]
Per our "conversation" at https://old.reddit.com/r/firefox/comments/f0gqcs/the_ublock_origin_developer_has_recently_released/fguianp/ I have opened an issue for this functionality. 

Default behavior could be it shows the subs that the site has and you have an "advanced user" checkbox similar to uBO that allows you to subsitute your own srt/vtt.

This would hopefully workaround the issue of Firefox's PIP window not being able to display subtitles.

**Comment by gkatsev** [comment]
I think this is currently a limitation of PiP. Likely needs to wait for browsers to allow native text tracks to be shown in PiP.

**Comment by gorhill** [comment]
> Default behavior could be it shows the subs that the site has

As long as you do not assign a text track, a video is left untouched, so whatever text track it has already present will be available as if CCaptioner was not installed.

> Firefox's PIP window not being able to display subtitles

https://bugzilla.mozilla.org/show_bug.cgi?id=1551058

**Comment by Movisivi** [comment]
Closing since Mozilla added their own subtitle support
