### ISSUE TITLE
Wrong character encoding

### ISSUE THREAD

**Issue by Sanyy** [gorhill/ccaptioner#3]
Hi,

"Strange" characters in hungarian sub these charcters are not shown correctly (only some kind of weird placeholder):

é: U+00E9
á: U+00E1
ő: U+0151
ö: U+00F6
ó: U+00F3
ű: U+0171

**Comment by gorhill** [comment]
Can't do anything without telling me everything I need to reproduce the issue on my side, without having me to search for anything. Provide details, and URLs to subtitles file which is causing you issue.

**Comment by Sanyy** [comment]
Movie file:
"local"

URL to subtitle:
https://www.feliratok.info/index.php?action=letolt&fnev=The.Walking.Dead.S10E09.WEBRip.x264-ION10.srt&felirat=1582554037

Played in Firefox and no issue in VLC with the file.

Note: I thought because of Firefox but when i tried to test with Iridium the addon could not catch the video.
-> My fault with Iridium had to enable File access for the addon but "weird" charcters are shown here too.

**Comment by gorhill** [comment]
Thanks for the information; I can reproduce, I will investigate.

**Comment by gorhill** [comment]
The file encoding is `ISO-8859-1` while I believe the browser uses the encoding of the web page -- likely UTF-8 -- to decode the text file. If I convert the file to `UTF-8` (using a simple text editor), the captions render fine.

Not sure what will be the solution for now -- detecting character encoding and converting to utf-8 if needed is not a trivial feature and for now I do not have much time to undertake this. As a workaround maybe see if your text editor can convert to utf-8.

**Comment by gorhill** [comment]
Reference, <https://en.wikipedia.org/wiki/SubRip#Text_encoding>:

> SubRip's default output encoding is configured as Windows-1252. However, output options are also given for many Windows code pages as well Unicode encodings, such as UTF-8 and UTF-16, with or without Byte Order Mark (BOM). Therefore, there's no de facto character encoding standard for .srt files, which means that any SubRip file parser must attempt to use Charset detection. Unicode Byte Order Mark (BOM) are typically used to aid detection.

**Comment by Sanyy** [comment]
I contact the guy "who did this". He might pay attention to this in the future.

till then i can convert it too:
iconv -f ISO-8859-1 -t UTF-8 The.Walking.Dead.S10E09.WEBRip.x264-ION10.srt -o The.Walking.Dead.S10E09.WEBRip.x264-ION10-UTF-8.srt

Thank you very much gorhill!

**Comment by gorhill** [comment]
Best to keep this opened, though I don't see the solution as trivial, ideally CCaptioner should seamlessly deal with encoding different than UTF-8.

**Comment by gorhill** [comment]
Fixed in 1.1.0.
